project_id = "nyxnvsaivmvllqevgmeh"

[functions.asaas-create-customer]
verify_jwt = false

[functions.asaas-create-subscription]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.asaas-checkout]
verify_jwt = false

[functions.send-payment-email]
verify_jwt = false
